---
repository:
  Ubuntu:
    name: "deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    key: "https://download.docker.com/linux/ubuntu/gpg"
  Debian:
    name: "deb https://download.docker.com/linux/debian {{ansible_distribution_release}} stable"
    key: "https://download.docker.com/linux/debian/gpg"
  Raspbian:
    name: "deb https://download.docker.com/linux/raspbian {{ansible_distribution_release}} stable"
    key: "deb https://download.docker.com/linux/raspbian/gpg"
debian_packages:
  docker_requirements:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  docker_common:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  docker_python:
  - python-docker
  - python-pip
  docker_python3:
  - python3-docker
  - python3-pip
ubuntu_packages:
  docker_common:
    - docker.io
