---
packages:
  docker_requirements:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  docker_common:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  docker_python:
  - python-docker
  - python-pip
  docker_python3:
  - python3-docker
  - python3-pip
