---
- name: "Creating the docker volume jellyfin config"
  docker_volume:
    name: jellyfin-config
    state: present

- name: "Creating the media-library directory"
  file:
    path: /var/local/media-library/
    state: directory

- name: "Starting container jellyfin-server image"
  docker_container:
    name: jellyfin-server
    image: linuxserver/jellyfin
    env:
      UID: "{{ uid }}"
      GID: "{{ gid }}"
      UMASK_SET: "{{ umask }}"
      TZ: "{{ timezone | default(ansible_date_time.tz) }}"
    detach: True
    ports: "{{ bind_ports | list }}"
    volumes:
      - jellyfin-config:/config
      - /var/local/media-library/:/media-library
      - /var/local/downloads/:/downloads
    restart_policy: always
    state: started
